server:
  port: 8001

# ==========applicationName + druid-mysql8 driver===================
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: liyajun123.
  profiles:
    active: dev # 多环境配置

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.zartt.cloud.entities
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
# ========================zipkin===================
management:
  zipkin:
    tracing:
      endpoint: http://117.72.38.46:32810/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。